### ISSUE TITLE
Hosting comments on GitHub for static websites

### ISSUE THREAD

**Issue by daniele-salvagni** [daniele-salvagni/dan.salvagni.io#1]

**Comment by daniele-salvagni** [comment]
Random comment to test this! 💖

**Comment by daniele-salvagni** [comment]
Random comment to test this! 🐙

**Comment by zipang** [comment]
That's a pretty nice hack ! :smirk_cat:
Is the whole site automatically regenerated when a new issue is posted ?

**Comment by zipang** [comment]
Well.. it is ! 👏 :stuck_out_tongue_winking_eye:

**Comment by daniele-salvagni** [comment]
Yes, comments are loaded in Javascript each time the page loads, so they will always be up to date.

**Comment by SigmaRS** [comment]
Very clever way to add comments to a website...
